name: CI

on:
  push:
    branches:
    - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout lammps/lammps-web
      uses: actions/checkout@v2

    - name: Checkout lammps/lammps
      uses: actions/checkout@v2
      with:
        repository: lammps/lammps
        path: lammps
        fetch-depth: 1

    - name: Install packages
      run: sudo apt-get install -y wget build-essential cmake git python3 npm

    - name: Install Emscripten
      run: |
        cd /opt
        git clone https://github.com/emscripten-core/emsdk.git
        cd /opt/emsdk
        ./emsdk install latest
        ./emsdk activate latest

    - name: Build LAMMPS and generate website
      run: ./build.sh

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./web/_site
